-- Material Data
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.Material" (id , "MaterialDescription", "ExpirationDays", "ExpirationType", "OrderingTreshold") VALUES (101, 'Soap Bars', 10, 'Perishable', 15);
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.Material" (id , "MaterialDescription", "ExpirationDays", "ExpirationType", "OrderingTreshold") VALUES (102, 'Whole Chicken', 5, 'Perishable', 5);
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.Material" (id , "MaterialDescription", "ExpirationDays", "ExpirationType", "OrderingTreshold") VALUES (103, 'Storage Bin', 200, 'Non-Perishable', 50);
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.Material" (id , "MaterialDescription", "ExpirationDays", "ExpirationType", "OrderingTreshold") VALUES (104, 'Broccoli Crowns', 10, 'Perishable', 42);
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.Material" (id , "MaterialDescription", "ExpirationDays", "ExpirationType", "OrderingTreshold") VALUES (105, 'Tortilla Chips', 5, 'Perishable', 8);
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.Material" (id , "MaterialDescription", "ExpirationDays", "ExpirationType", "OrderingTreshold") VALUES (106, '2% Skim Milk', 200, 'Perishable', 3);
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.Material" (id , "MaterialDescription", "ExpirationDays", "ExpirationType", "OrderingTreshold") VALUES (107, 'Electric Kettle', 200, 'Non-Perishable', 53);
-- Inventory Data
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.Inventory" (id , "ProductDescription", "Price", "Currency", "ShelfStock", "Location", "Image", "Status", "StatusColor", "StoringInstruction", "InStock", "Unit", "LifeRemaining", "LifeRemainingTreshold", "ItemType", "OrderingTreshold") VALUES (00002364, 'Broccoli Crowns', '2,99', 'USD', '27', 'Aisle 3, Section 5', 'assets/broccolli.png', 'Deteriorating', 'Error', 'Keep humidity level between 15% to 35%. Temperature between 3 - 6 °C', '190', 'Bags', '10', 'Error', 'Perishable', '10');
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.Inventory" (id , "ProductDescription", "Price", "Currency", "ShelfStock", "Location", "Image", "Status", "StatusColor", "StoringInstruction", "InStock", "Unit", "LifeRemaining", "LifeRemainingTreshold", "ItemType", "OrderingTreshold") VALUES (1015346, 'Tortilla Chips', '4,99', 'USD', '35', 'Aisle 17, Section 5', 'assets/tortillachips.png', 'In-Stock', 'Success', 'Store in room temperate', '180', 'Boxes', '20', 'Success', 'Non-Perishable', '11');
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.Inventory" (id , "ProductDescription", "Price", "Currency", "ShelfStock", "Location", "Image", "Status", "StatusColor", "StoringInstruction", "InStock", "Unit", "LifeRemaining", "LifeRemainingTreshold", "ItemType", "OrderingTreshold") VALUES (1564789, 'Soap Bars', '5,49', 'USD', '3', 'Aisle 23, Section 21', 'assets/soap.png', 'Re-Stock', 'Error', 'Store in room temperate', '5', 'Boxes', '100', 'Success', 'Non-Perishable', '12');
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.Inventory" (id , "ProductDescription", "Price", "Currency", "ShelfStock", "Location", "Image", "Status", "StatusColor", "StoringInstruction", "InStock", "Unit", "LifeRemaining", "LifeRemainingTreshold", "ItemType", "OrderingTreshold") VALUES (0012879, '2% Skim Milk', '5,99', 'USD', '35', 'Aisle 12, Door 3', 'assets/milk.png', 'In-Stock', 'Success', 'Keep humidity level between 15% to 35%. Temperature between 3 - 6 °C', '100', 'Cartons', '50' 'Success', 'Perishable', '13');
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.Inventory" (id , "ProductDescription", "Price", "Currency", "ShelfStock", "Location", "Image", "Status", "StatusColor", "StoringInstruction", "InStock", "Unit", "LifeRemaining", "LifeRemainingTreshold", "ItemType", "OrderingTreshold") VALUES (006548, 'Lettuce', '6,79', 'USD', '35', 'Aisle 3, Section 4', 'assets/lettuce.png', 'Re-Stock', 'Error', 'Keep humidity level between 15% to 35%. Temperature between 3 - 6 °C', '80', 'Bags', '15', 'Error', 'Perishable', '14');
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.Inventory" (id , "ProductDescription", "Price", "Currency", "ShelfStock", "Location", "Image", "Status", "StatusColor", "StoringInstruction", "InStock", "Unit", "LifeRemaining", "LifeRemainingTreshold", "ItemType", "OrderingTreshold") VALUES (0022865, 'Whole Chicken', '3,99', '/LB', '35', 'Aisle 7, Section 17', 'assets/chicken.png', 'In-Stock', 'Success', 'Keep humidity level between 15% to 35%. Temperature between 3 - 6 °C', '50', 'LB', '60', 'Success', 'Perishable', '15');
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.Inventory" (id , "ProductDescription", "Price", "Currency", "ShelfStock", "Location", "Image", "Status", "StatusColor", "StoringInstruction", "InStock", "Unit", "LifeRemaining", "LifeRemainingTreshold", "ItemType", "OrderingTreshold") VALUES (3065789, 'Storage Bin', '7,99', 'USD', '19', 'Aisle 27, Section 9', 'assets/storagebin.png', 'In-Stock', 'Success', 'Store in room temperate', '20', 'PCS', '50', 'Success', 'Non-Perishable', '16');
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.Inventory" (id , "ProductDescription", "Price", "Currency", "ShelfStock", "Location", "Image", "Status", "StatusColor", "StoringInstruction", "InStock", "Unit", "LifeRemaining", "LifeRemainingTreshold", "ItemType", "OrderingTreshold") VALUES (3200159, 'Electric Kettle', '10,99', 'USD', '10', 'Aisle 24, Section 36', 'assets/kettle.png', 'In-Stock', 'Success', 'Store in room temperate', '10', 'PCS', '10', 'Success', 'Non-Perishable', '17');

-- RequisitionHeader Data
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.RequisitionHeader" (id , "RequisitionDescription", "RequisitionDate", "RequisitionStatus") VALUES (201, 'Friday Requisition', '2019-06-10', 'Open');
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.RequisitionHeader" (id , "RequisitionDescription", "RequisitionDate", "RequisitionStatus") VALUES (202, 'May Requisitions', '2019-06-01', 'Closed');

-- RequisitionItem Data
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.RequisitionItem" (id, "ItemDescription", "Quantity", "Unit", "RequisitionHeader.ID") VALUES (10, 'Food', 10, 'kg', 201);
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.RequisitionItem" (id, "ItemDescription", "Quantity", "Unit", "RequisitionHeader.ID") VALUES (20, 'Devices', 8, '-', 201);
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.RequisitionItem" (id, "ItemDescription", "Quantity", "Unit", "RequisitionHeader.ID") VALUES (30, 'Kitchen equipment', 20, 'Pieces', 201);
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.RequisitionItem" (id, "ItemDescription", "Quantity", "Unit", "RequisitionHeader.ID") VALUES (40, 'Food', 15, 'kg', 202);

-- Locations Data
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.Locations" (id , "LocationDescription", "Building", "Floor", "Room") VALUES (101, 'BG F.5 K.B', 'BG', 'Floor 5', 'Kitchen blue');
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.Locations" (id , "LocationDescription", "Building", "Floor", "Room") VALUES (102, 'BG F.5 K.Y', 'BG', 'Floor 5', 'Kitchen yellow');
INSERT INTO "hkrbudgetingdb.db.dbmodel::hkrbudgeting.Locations" (id , "LocationDescription", "Building", "Floor", "Room") VALUES (103, 'BG F.5 K.G', 'BG', 'Floor 5', 'Kitchen green');